use_frameworks!

target 'JMTextView_Example' do
  pod 'JMTextView', :path => '../'

  target 'JMTextView_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.0.0'
  pod 'Nimble', '~> 5.1.1'
  end
end
